[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "check-merge-conflict" },
  { id = "check-symlinks" },
  { id = "destroyed-symlinks" },
  { id = "forbid-new-submodules" },
  { id = "detect-private-key" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
language = "system"
entry = "cargo +nightly fmt --all -- --check"
types_or = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "cargo-test"
name = "cargo test"
language = "system"
entry = "cargo test --verbose --all"
always_run = true
pass_filenames = false
