on:
  pull_request:
  push:
    branches:
      - main
      - master

name: Continuous Integration

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - uses: j178/prek-action@v2
        with:
          extra-args: --all-files --skip cargo-test

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ 1.88.0, stable, beta, nightly ]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo test --workspace

  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo publish --dry-run
