on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install stable --profile minimal
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo +stable publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
